### ISSUE TITLE
Funds Distribution Upon Cancellation

### ISSUE THREAD

**Issue by patriacaelum** [patriacaelum/proposal-inverter#17]
There was a big concern over how funds were distributed when a proposal is cancelled. We should address these as soon as possible.

- [x] Brokers are promised funding for a certain number of epochs, and any leftover funding should be returned back to funders. Should the remaining funding be distributed proportionally to funders? Should priority be given to more recent funders?
- [ ] Shawn brought up the point that it would be most advantageous for brokers to stake on proposals that are close to cancellation so that they are able to get the most funds with the least amount of work. How do we address this? Should new brokers under the minimum number of epochs not receive a full share of funds? Or does the whitelisting mechanism prevent this?

**Comment by MoatazAR** [comment]
1- Maybe we can have another buffer period, where if the buffer period passes for a funder without him adding an additional investment, then that funder doesn't receive a portion. Another method we could try is to make it more contribution-centric than time-centric, as in, the funder that provided a larger portion of funds is entitled to a larger portion.
2-  This issue is a bit more difficult to tackle. I think the first option is better, cuz Im not sure how the whitelisting mechanism would even prevent this.

**Comment by xm3van** [comment]
Adding my thoughts here as well - I would argue that both should be parameter setting that should be user defined before the deployment of the PI. Depending on the use case and trust assumptions, it would be good to customise this. 

1. Default case could be, however, something like this for a given project per founder: Remaining_funds_of_given_commitment = funding_amount - (funded_share_per_epoch* no_epochs_past). This favours newer funding member but the way I would view this is that a funder enter a commitment to fund a project, thus paying for it's maintenance per epoch (i.e. each epoch funds deplete). If a funder funds twice this in beginning and after x epochs this should also seen as two separate funding commitment. 

2. Personally I think whitelist prevents this - not technically but through a social layer. Key thing to consider is however that this may limit use cases as we make a trust assumption that brokers are trusted and thus behave.

**Comment by MoatazAR** [comment]
> Adding my thoughts here as well - I would argue that both should be parameter setting that should be user defined before the deployment of the PI. Depending on the use case and trust assumptions, it would be good to customise this.
> 
> 1. Default case could be, however, something like this for a given project per founder: Remaining_funds_of_given_commitment = funding_amount - (funded_share_per_epoch* no_epochs_past). This favours newer funding member but the way I would view this is that a funder enter a commitment to fund a project, thus paying for it's maintenance per epoch (i.e. each epoch funds deplete). If a funder funds twice this in beginning and after x epochs this should also seen as two separate funding commitment.
Can you specify what each variable is? cuz I'm not sure what the difference between funding_amount and funded_share_per_epoch is. Also I don't know what no_epochs_past is referring to.
> 2. Personally I think whitelist prevents this - not technically but through a social layer. Key thing to consider is however that this may limit use cases as we make a trust assumption that brokers are trusted and thus behave.
