### ISSUE TITLE
Accomodate multiple tokens

### ISSUE THREAD

**Issue by patriacaelum** [patriacaelum/proposal-inverter#24]
- [x] Add multiple funds to the initial conditions
- [x] the funds parameter should be a dictionary that maps the token name with the amount `funds = {"TEC": 10, "GTC": 24}`
- [x] Create USD equivalent oracles to the different tokens, "1 TEC = 2USD", or "1 GTC = 0.24", you can use a random stochastic process or use historical data
- [x] Change the distribution when the epoch is iterated so that a proportional amount of tokens is distributed, so if the allocation per epoch is $1000, and the pool is 70% GTC and 30% TEC, then 70% of the $1000 is in GTC and 30% of the $1000 is in TEC

**Comment by patriacaelum** [comment]
Should brokers be forced to stake using the same tokens as the funders? In other words, should brokers be allowed to stake using any kind of currency, as long as it has an equivalent value at the time of joining?

**Comment by MoatazAR** [comment]
I think so, it doesn't make sense to force brokers to use the same currency the owner used
